<a href="https://colab.research.google.com/github/Hinna0818/DL-self-practice/blob/main/1tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## create tensor data
import numpy as np
import torch
x = [[1,2], [3,4]]
data = torch.tensor(x)
print(data)

tensor([[1, 2],
        [3, 4]])


In [2]:
## convert into ndarray
x_np = np.array(x)
x_tensor = torch.from_numpy(x_np)
print(x_tensor)

tensor([[1, 2],
        [3, 4]])


In [3]:
## from another tensor
x_ones = torch.ones_like(x_tensor)
x_rand = torch.rand_like(x_tensor, dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3205, 0.1997],
        [0.9125, 0.8315]])


In [4]:
## with random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
zero_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)

print(rand_tensor)
print(zero_tensor)
print(ones_tensor)

tensor([[0.5625, 0.7445, 0.1246],
        [0.7204, 0.3850, 0.8482]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
t = torch.rand(3, 4)
print(f"Shape of tensor: {t.shape}")
print(f"datatype of tensor: {t.dtype}")
print(f"device of tensor: {t.device}")

Shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu


operations on tensor

In [9]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    t = t.to(torch.accelerator.current_accelerator())

print(f"device of tensor: {t.device}")

device of tensor: cuda:0


In [11]:
## splice
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}")
print(f"second column: {tensor[:, 1]}")
print(f"last column: {tensor[..., -1]}")

tensor[:, 1] = 0
print(f"shifted tensor {tensor}")

first row: tensor([1., 1., 1., 1.])
second column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
shifted tensor tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
## bind
# rbind
t1 = torch.cat([tensor, tensor], dim = 1)
print(f"binding by rows \n {t1}")

t2 = torch.cat([tensor, tensor], dim = 0)
print(f"binding by columns \n {t2}")

binding by rows 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])
binding by columns 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
## matrix multiplication
tensor = torch.rand(4, 3)
y1 = tensor @ tensor.H
y2 = tensor.matmul(tensor.H)
print(y1)
print(y2)

tensor([[0.8932, 1.2434, 0.4374, 0.9254],
        [1.2434, 2.1117, 0.7394, 1.7405],
        [0.4374, 0.7394, 0.2887, 0.5670],
        [0.9254, 1.7405, 0.5670, 1.5527]])
tensor([[0.8932, 1.2434, 0.4374, 0.9254],
        [1.2434, 2.1117, 0.7394, 1.7405],
        [0.4374, 0.7394, 0.2887, 0.5670],
        [0.9254, 1.7405, 0.5670, 1.5527]])


In [18]:
## element-wise product
y3 = tensor * tensor
y4 = tensor.mul(tensor)
print(y3)
print(y4)

tensor([[0.2257, 0.5989, 0.0685],
        [0.2562, 0.9480, 0.9075],
        [0.0013, 0.1920, 0.0953],
        [0.2551, 0.3002, 0.9974]])
tensor([[0.2257, 0.5989, 0.0685],
        [0.2562, 0.9480, 0.9075],
        [0.0013, 0.1920, 0.0953],
        [0.2551, 0.3002, 0.9974]])


In [24]:
print(tensor.sum())
print(tensor.sum(axis = 0))
print(tensor.sum(axis = 1))

## .item生成python原类型数据
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(6.7786)
tensor([1.5231, 2.7336, 2.5219])
tensor([1.5108, 2.4325, 0.7837, 2.0517])
6.778636932373047 <class 'float'>


与numpy的交互

In [26]:
## torch到numpy
t = torch.ones(3,4)
n = t.numpy()
print(f"torch: \n{t}")
print(f"numpy: \n{n}")

torch: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
numpy: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
## 二者在cpu共享内存，一个修改会影响另一个
t.add_(2)
print(t)
print(n)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [29]:
## numpy到torch
n = np.ones(4)
t = torch.from_numpy(n)

print(f"numpy: \n{n}")
print(f"torch: \n{t}")

numpy: 
[1. 1. 1. 1.]
torch: 
tensor([1., 1., 1., 1.], dtype=torch.float64)
