In [2]:
## create tensor data
import numpy as np
import torch
x = [[1,2], [3,4]]
data = torch.tensor(x)
print(data)

tensor([[1, 2],
        [3, 4]])


In [3]:
## convert into ndarray
x_np = np.array(x)
x_tensor = torch.from_numpy(x_np)
print(x_tensor)

tensor([[1, 2],
        [3, 4]])


In [5]:
## from another tensor
x_ones = torch.ones_like(x_tensor)
x_rand = torch.rand_like(x_tensor, dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9270, 0.6752],
        [0.9702, 0.2794]])


In [6]:
## with random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
zero_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)

print(rand_tensor)
print(zero_tensor)
print(ones_tensor)

tensor([[0.4187, 0.3635, 0.9739],
        [0.5836, 0.4680, 0.6021]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
